id: PC5B524CE
initial_creation_type: ocr
source_metadata:
  volumes:
    0eb493e492af4e29a426583a2548b6fc:
      base_file: v018.txt
      image_group_id: I1PD95850
      title: རིམ་པ་ལྔ་པ།
      total_pages: 2069
      volume_number: 18
