id: DD4FE7D65
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T07:06:44+00:00'
last_modified: '2022-05-26T07:51:52.105230+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    b1e0:
      image_group_id: I1PD95863
      title: རིམ་པ་ལྔ་པ།
      total_pages: 2069
      order: 18
      base_file: b1e0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
